name: CI

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Setup Chomp
        uses: guybedford/chomp-action@v1
      - run: yarn
      - run: yarn run build
      - run: yarn run test
      - name: Authenticate with Registry
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm logout
          echo "@jspm:registry=https://registry.npmjs.org/" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami

      - name: Publish to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --yes
